export {Home} from "./home/Home"
export {Login} from "./login/Login"
export {Signup} from "./signup/Signup"
export {Rules} from "./rules/Rules"
export {ProfilePage} from "./profilePage/ProfilePage"
export {Question} from "./currentQuestion/Question"
export {Result} from "./result/Result"
export {Board} from "./leaderBoard/Board"